apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: client
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: client
            image: smqasims/client
            args:
            - http://$(SERVER_SERVICE_HOST):$(SERVER_SERVICE_PORT)
          restartPolicy: Never
