apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: "localhost:5000/server:v2"
          ports:
          - containerPort: 8080
