apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: smqasims/server:v2
          ports:
          - containerPort: 8080
